### ISSUE TITLE
AWS.AvailabilityZones ignored / overwritten

### ISSUE THREAD

**Issue by troytop** [colstrom/cloudstrap#17]
I've been specifying 'AWS.AvailabilityZones = us-east-1c' in my bootstrap.properties file (local), but once cloudstrap has finished processing it, it ends up 'AWS.AvailabilityZones=us-east-1a' and that's where my instances end up.

**Comment by colstrom** [comment]
This was discussed offline, but recording here for record-keeping.

This is intentional. Cloudstrap configures bootstrap.properties to match what it created. It does not use any settings from it, those only exist to be passed on to hcp-bootstrap.

Also, as of 53efd48 seed properties are no longer required.
